### ISSUE TITLE
string length (143) exceeds the limit 128

### ISSUE THREAD

**Issue by NehaPeer** [basecamp/local_time#117]
using 

Rails 6.1.5
Ruby 3.1.1

Installed latest gem local_time (2.1.0) 

Below is the code - 
```
dateTime is variable.
<%local_time = local_time(dateTime,format: '%Y-%m-%d %H:%M %Z',title: "#{dateTime}") if   !dateTime.blank?%>
        
<%callrun = Time.parse local_time%>
```

**Comment by josefarias** [comment]
The `local_time` helper returns an html `<time>` element – which `Time::parse` wouldn't be able to process. That is just not the intended use of this library.

It looks like the string length error message would be raised by `Time::parse` in this scenario.

**Comment by rubyFeedback** [comment]
I just ran into this issue. I find it weird that ruby generates a message based on this limit.

Admittedly my String is super-long and one can reason that this was a wrong string,
but even in that case I would reason that Time-related methods SHOULD try to cope
with it, rather than present this arbitrary limitation.
