### ISSUE TITLE
Time is printed twice, in different zones

### ISSUE THREAD

**Issue by siruguri** [basecamp/local_time#118]
We are using `local_time` in our Rails 6.1 app, v2.1.0 of the Node module. It generates all the date times in the below screenshot, but for some reason one of them, in the 2nd row, appears in both zones:

<img width="1778" alt="Screen Shot 2022-05-16 at 12 42 51 PM" src="https://user-images.githubusercontent.com/40653/168652262-3bdd9b73-63c6-4949-a861-64df96191165.png">

The HTML attributes appear to be the same on this element as on the other elements.

**Comment by mustafa90** [comment]
I also have the same issue and I am using active admin along with it.

**Comment by josefarias** [comment]
I see a couple thumbs up and a comment on this issue – wondering if someone has a bit more information on this one. Can anyone share a minimal reproduction or an explanation, assuming they figured it out?

I unfortunately haven't run into this myself and I don't see any obvious bugs in the code. So I don't have much to go on in order to fix this.
