### ISSUE TITLE
New release for 24hr support

### ISSUE THREAD

**Issue by jankoegel** [basecamp/local_time#146]
I tried adding this gem to my Rails app today and wanted to use the `LocalTime.config.useFormat24 = true` option the README mentions.
It took me a while to figure out that the library code to handle this is still missing from the latest release.

Could you please make a new release so the README matches the library's behaviour?

Thank you so much & keep up the great work.

**Comment by josefarias** [comment]
Hey @jankoegel

The way we build this library changed since the last release. I want to do some testing to make sure the new builds are requireable in the most common setups before releasing. Also, there are a few outstanding PRs I'd love to get into the next release — but that's not a blocker, just something that's also in-flight.

In the meantime, if you're willing to run with the unreleased version, you can point your dependencies to the `main` branch. The latest JS builds are checked into the repo, too. Definitely let us know how it goes if you do this!

I'll keep this open, as this is actively on my mind. But I need to find the time to do it as we're currently in the middle of a cycle, working on unrelated projects.

**Comment by a-nickol** [comment]
I had the same problem and ended up using it as a git submodule and reference the gem & npm package locally.

**Comment by josefarias** [comment]
Just cut a new release. Let me know if you run into trouble. Thanks!
