### ISSUE TITLE
I dont want it to wrap date with <time> tag

### ISSUE THREAD

**Issue by shivabhusal** [basecamp/local_time#40]
I have been using [local_time][1] to convert servertime to client local time. However now I am using [datatables][2] and to sort `date/time` columns. I have to use `date-moment.js` plugin of `Datatables` which uses [moment.js][3] to handle date conversions.

My problem is: the `local_time`'s view helper is wrapping the date with `< time >` tag like this 

    <time data-format="%B %e, %Y %l:%M%P"
          data-local="time"
          datetime="2013-11-27T23:43:22Z"
          title="November 27, 2013 6:43pm EDT"
          data-localized="true">November 27, 2013 6:43pm</time>

The wrapping thing is creating problem for `moment.js` to get the actual `date-time` as it expects. I need it to convert the `date-time` but not wrap with `<time>` tag. Is it possible. If yes How?

  [1]: https://github.com/basecamp/local_time
  [2]: https://www.datatables.net/
  [3]: http://momentjs.com/docs/

**Comment by javan** [comment]
Hi @shivabhusal, no plans to support customizing the tag currently. Perhaps you can preprocess the `<time>` time tags with JavaScript to convert or unwrap them as desired. Or since moment.js can parse UTC times and display them as local times (http://www.digitoffee.com/programming/get-local-time-utc-using-moment-js/94/), maybe you don't need local_time at all.
